import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import "./globals.css";
import { Noto_Sans_JP, Noto_Serif_JP } from "next/font/google";

const notoJP = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-noto-jp",
});
const notoSerifJP = Noto_Serif_JP({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-noto-serif-jp",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body className={`${notoJP.variable} ${notoSerifJP.variable} min-h-full flex flex-col`} cz-shortcut-listen="true" >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
